#!sh 
gcc -std=c++11 -I/opt/homebrew/include -L/opt/homebrew/lib  -o ss -lc++ -lc -lcurl -lpcre2-8 -lresolv -lssl -lcrypto main.cpp WS.cpp utils.cpp Template.cpp DNSQuery.cpp Headers.cpp



# -I/Library/Developer/CommandLineTools/SDKs/MacOSX15.1.sdk/usr/include -L/Library/Developer/CommandLineTools/SDKs/MacOSX15.1.sdk/usr/lib/system
